[package]
name = "demo-router"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true

[dependencies]
axum.workspace = true
dashmap.workspace = true
serde.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
tokio-stream.workspace = true
futures-util.workspace = true
