[package]
name = "demo-router"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
rust-version.workspace = true

[dependencies]
portal-types.path = "../portal-types"

async-trait.workspace = true
axum.workspace = true
axum-extra.workspace = true
dashmap.workspace = true
jsonwebtoken.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
tokio-stream.workspace = true
futures-util.workspace = true

[dev-dependencies]
clap.workspace = true