name = "portal-router"
workers_dev = true
compatibility_date = "2024-03-18"
main = "build/worker/shim.mjs"

[build]
command = "worker-build --release && rm -rf ../../cf/build && mv build ../../cf/"
cwd = "../crates/portal-router"

[[durable_objects.bindings]]
name = "TUNNEL"
class_name = "DurableRouter"

[[migrations]]
tag = "v1"
new_classes = ["DurableRouter"]
