[workspace.package]
rust-version = "1.69.0"

[workspace]
resolver = "2"
members = [
    "portal-router",
    "jwt-webcrypto",
]

[workspace.dependencies]
async-trait = "0.1.77"
base64 = { version = "0.21.7", default-features = false, features = ["alloc"] }
console_error_panic_hook = { version = "0.1.7" }
futures = "0.3.30"
js-sys = "0.3.67"
pem = { version = "3.0.3", default-features = false }
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
worker = { git = "https://github.com/eric-seppanen/workers-rs.git", branch = "local" }
worker-sys = { git = "https://github.com/eric-seppanen/workers-rs.git", branch = "local" }
wasm-bindgen = "0.2.86"
wasm-bindgen-futures = "0.4.40"
wasm-bindgen-test = "0.3.40"
web-sys = { version = "0.3.67", features = ["Crypto", "CryptoKey", "SubtleCrypto", "HmacImportParams", "EcKeyImportParams", "EcdsaParams", "Window", "console"] }

jwt-webcrypto = { path = "jwt-webcrypto" }
